name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main
      - name: Deps
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y devscripts debhelper
          sudo apt install -y meson git pkgconf sed gettext
          sudo apt install -y libcap2-bin libcap-dev libidn2-dev
      - name: Std build
        run: |
          meson setup _build
          meson compile -C _build
      - name: Meson tests
        run: |
          sudo /sbin/setcap cap_net_raw+p ./_build/ping/ping
          meson test -C _build
      - name: Build .deb packages
        run: dpkg-buildpackage -us -uc
      - name: Install .deb packages (except arping and clockdiff)
        run: |
          sudo apt install -y ../iputils99-ping_*.deb
          sudo apt install -y ../iputils99-tracepath_*.deb
          sudo apt install -y ../iputils99-gai_*.deb
      - name: Test tools
        run: |
          echo "ping/tracepath/gai"
          echo ""
          echo ">>> ping"
          ping -c10 localhost
          echo ""
          echo ">>> tracepath"
          tracepath localhost
          echo ""
          echo ">>> getaddrinfo wrapper"
          gai one.one.one.one

