# Copyright (c) 2021 Petr Vorel <pvorel@suse.cz>

name: "CI: docker based builds"

jobs:
  job:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - container: "debian:stable"
            env:
              CC: gcc
    container:
      image: ${{ matrix.container }}
      env: ${{ matrix.env }}
      options: --security-opt seccomp=unconfined

    steps:
    - name: Show OS
      run: cat /etc/os-release

    - name: Git checkout
      uses: actions/checkout@v1

    - name: Install additional packages
      run: |
        export INSTALL=${{ matrix.container }}
        export DISTRO_VERSION="${INSTALL#*:}"
        INSTALL="${INSTALL#quay.io/centos/}"
        INSTALL="${INSTALL%%:*}"
        INSTALL="${INSTALL%%/*}"
        ./ci/$INSTALL.sh
        if [ "$VARIANT" ]; then ./ci/$INSTALL.$VARIANT.sh; fi

    - name: Check dependencies
      run: ./build.sh dependencies

    - name: Check info
      run: ./build.sh info

    - name: Configure
      run: ./build.sh configure

    - name: Compile
      run: ./build.sh build

    - name: Show build log
      run: ./build.sh build-log

    - name: Install
      run: ./build.sh install

    - name: Show install log
      run: ./build.sh install-log

    - name: Run tests
      run: if [ ! "$SKIP_TESTS" ]; then ./build.sh test; else echo "tests skipped"; fi

    - name: Show test log
      run: ./build.sh test-log
